# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4afe64896786fb7efa989a2a674e4a8197561a49cc4f6e3afae30e34092c419ea3c069b21465233584fc69d4abfee466304e77c2564cb5e184d99af25bcdc4ac

test:
  secret_key_base: 3a6c2035eba3653fd40238d4874f3bd7db1a7f06b7e03d636d47441685b4c7ce4423ee119dc1cfebec0fc802942cba68c01745da15d2edc2e716a3fcce09e4fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
